name: Notify chat about (re)opened issue
on:
  issues:
    types:
      - opened
      - reopened

env:
  message: <a href='${{ github.server_url }}/${{ github.repository }}/issues/${{ github.event.issue.number }}'>Issue ${{ github.event.issue.number }}</a> ${{ github.event.issue.event }} in ${{ github.repository }} by ${{ github.actor }}

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: "Exec webhook call"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "GitHub", "format": "html", "text": "${{ env.message }}" }'
        timeout: 1000
        retries: 2
