name: Send message to chat
on:
  issues:
    types:
      - opened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: olabiniV2/matrix-message@v0.0.1
       with:
         room_id: ${{ secrets.ELEMENT_ROOM_ID }}
         access_token: ${{ secrets.ELEMENT_ACCESS_TOKEN }}
         subject: "Github"
         message: "Job executed on $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
         server: "riot.netresearch.de"
