name: Send message to chat
on:
  issues:
    types:
      - opened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -H "Content-Type: application/json" --data '{ "displayName": "Github", "format": "html", "text": "Test from $GITHUB_SERVER_URL/$GITHUB_REPOSITORY" }' ${{ secrets.WEBHOOK_URL }}
