name: Send message to chat
on:
  issues:
    types:
      - opened

env:
  github_actor: test1

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: "Call API"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200,201
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "Github",  "format": "html", "text": "New issue by ${{ env.github_actor }} ${{ github.ref }}" }'
        timeout: 1000
        retries: 2
