name: Send message to chat
on:
  issues:
    types:
      - opened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: Chat notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_USERNAME: Github (rtBot)
        SLACK_TITLE: Message
        SLACK_MESSAGE: "New issue created by ${{ GITHUB_ACTOR }}"
        MSG_MINIMAL: true
        SLACK_FOOTER: ""
