name: Send message to chat
on:
  issues:
    types:
      - opened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: Send message
      id: Github
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'riot.netresearch.de'
        token: ${{ secrets.ELEMENT_ACCESS_TOKEN }}
        channel: ${{ secrets.ELEMENT_ROOM_ID }}
        message: |
          Test message from $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
