name: Notify chat about (re)opened issue
on:
  [ issues, issue_comment ]

env:
  issue_link: <a href='${{ github.server_url }}/${{ github.repository }}/issues/${{ github.event.issue.number }}'>Issue ${{ github.event.issue.number }}</a> '${{ github.event.issue.title }}'

jobs:
  send_msg_issue_open:
   runs-on: ubuntu-latest
   if: issues.action == 'opened' || issues.action == 'reopened'
   steps:
    - name: "Exec webhook call"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "GitHub", "format": "html", "text": "${{ env.issue_link }} ${{ issues.action }} by ${{ github.actor }} in ${{ github.repository }}" }'
        timeout: 1000
        retries: 2
  send_msg_new_comment:
   runs-on: ubuntu-latest
   if: github.event.issue_comment.action == 'created'
   steps:
    - name: "Exec webhook call"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "GitHub", "format": "html", "text": "${{ env.issue_link }} in repo ${{ github.repository }} has new comment from ${{ github.actor }}" }'
        timeout: 1000
        retries: 2
