name: Send message to chat
on:
  issues:
    types:
      - opened

env:
  json_body: '{ \"displayName\": \"Github\",  \"format\": \"html\", \"text\": \"New issue by $GITHUB_ACTOR<br>$GITHUB_SERVER_URL/$GITHUB_REPOSITORY\" }'

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: "Call API"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200,201
        headers: '{ "Content-Type": "application/json" }'
        body: ${{ env.json_body }}
        timeout: 1000
        retries: 2
