name: Notify chat about (re)opened issue
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: "Webhook call"
      uses: indiesdev/curl@v1.1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        method: "POST"
        accept: 200,201
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "Github",  "format": "html", "text": "Issue ${{ github.event.issue.number }} opened in ${{ github.repository }} by ${{ github.actor }}.<br>See ${{ github.server_url }}/${{ github.repository }}/issues?q=involves%3A${{ github.actor }}+is%3Aopen" }'
        timeout: 1000
        retries: 2
