name: Send message to chat
on:
  issues:
    types:
      - opened

jobs:
  send_msg:
   runs-on: ubuntu-latest
   steps:
    - name: "Call API"
      uses: indiesdev/curl@v1.1
      with:
        url: https://reqres.in/api/users
        method: "POST"
        accept: 200
        headers: '{ "Content-Type": "application/json" }'
        body: '{ "displayName": "Github",  "format": "html", "text": ":info: New issue by $GITHUB_ACTOR<br>$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" }'
        timeout: 1000
        retries: 2
